# Mengatur prefix ke Ctrl+a (opsional, ganti jika sudah punya)
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Membuka split horizontal dengan prefix + h
bind h split-window -h

# Membuka split vertical dengan prefix + v
bind v split-window -v
