set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# setting
source-file '~/.config/tmux/keymaps.conf'
source-file '~/.config/tmux/options.conf'

# plugins
source-file '~/.config/tmux/conf.d/pomodoro.conf'

run '~/.config/tmux/plugins/tpm/tpm'
