set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# setting
source-file "$HOME/.config/tmux/keymaps.conf"
source-file "$HOME/.config/tmux/options.conf"

# plugins
source-file "$HOME/.config/tmux/conf.d/pomodoro.conf"

run "$HOME/.tmux/plugins/tpm/tpm"
